module.exports = [
   {
      name: "countryCode",
      value: "TR",
      domain: ".trendyol.com",
      path: "/",
      expires: -1,
      size: 13,
      httpOnly: false,
      secure: true,
      session: true,
      sameSite: "Lax",
      sameParty: false,
      sourceScheme: "Secure",
      sourcePort: 443,
   },
   {
      name: "storefrontId",
      value: "1",
      domain: ".trendyol.com",
      path: "/",
      expires: -1,
      size: 14,
      httpOnly: false,
      secure: true,
      session: true,
      sameSite: "Lax",
      sameParty: false,
      sourceScheme: "Secure",
      sourcePort: 443,
   },
   {
      name: "language",
      value: "tr",
      domain: ".trendyol.com",
      path: "/",
      expires: -1,
      size: 10,
      httpOnly: false,
      secure: true,
      session: true,
      sameSite: "Lax",
      sameParty: false,
      sourceScheme: "Secure",
      sourcePort: 443,
   },
];
